handler: lambdas/get-files/get-files.handler
name: get-files
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/get-files/get-files.js
    - lambdas/get-files/helpers/**
events:
  - http:
      method: get
      path: /
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint allows user to retrieve the list of files located at a given path inside of Kaskadi's public AWS S3 bucket.
        queryStringParameters:
          - key: path
            description: Path from where we would like to list files.
            default: /
        examples:
          - request:
              queryStringParameters:
                path: modules
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                - type: folder
                  size: 0
                  lastModified: '2020-01-14T15:07:20.000Z'
                  path: modules/@kaskadi/
                - type: folder
                  size: 6272
                  lastModified: '2020-01-14T15:20:06.000Z'
                  path: modules/@webcomponents/
                - type: folder
                  size: 0
                  lastModified: '2020-03-09T07:30:12.000Z'
                  path: modules/lit-element/
                - type: folder
                  size: 0
                  lastModified: '2020-03-09T07:30:13.000Z'
                  path: modules/lit-html/
