service:
  name: files-api
package:
  individually: true
  exclude:
    - '**/**'
plugins:
  - serverless-aws-documentation
  - serverless-offline
custom:
  documentation:
    api:
      info:
        version: 1.0.0
        title: ${self:service.name}
        description: API to manage files in S3
provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  apiName: ${self:service.name}
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags:
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: files
    type: http
functions:
  GetFiles: ${file(./lambdas/get-files/serverless.yml)}
layers:
  ApiLayer: ${file(./layer/serverless.yml)}
