handler: lambdas/get-signed-url/get-signed-url.handler
name: get-signed-url
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/get-signed-url/get-signed-url.js
    - lambdas/get-signed-url/helpers/**
events:
  - http:
      method: post
      path: get-signed-url
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint provides a way for users to get signed URLs that allows them to upload content into Kaskadi's public AWS S3 bucket.
        body:
          - key: key
            description: Key of the item you would like to upload on S3. Uses `/` as a separator to determine pseudo-folder structure to create on S3.
